### PR TITLE
Added Juck Juck Go Image

### PR DESCRIPTION
**Pull request by ItzSudhan**
### What I did here?
- Added Juck Juck Go Image
- Added the path to .json

### CODE REVIEW

**Comment by ItzSudhan** [comment]
Its going to be 1 year since i made this pr ;-;

**Comment by ItzSudhan** [comment]
its 1 year :yay:

**Comment by ItzSudhan** [comment]
2 years :poggers:

**Comment by khalby786** [comment]
After 2 years of carefully reviewing this PR, it LGTM.

**Pull request merged**
